### ISSUE TITLE
Creation of procedure in report failed (this.memberAttributes is not iterable)

### ISSUE THREAD

**Issue by wbrakowski** [DavidFeldhoff/al-codeactions#105]
Hi David,
I tried to create a procedure in a very simple report and got the following error message.
Please ignore the nonsense code, this is just a quick and dirty correction report.

![image](https://user-images.githubusercontent.com/53928639/106442624-c7c0fa00-647b-11eb-98ea-59dfa4f9a10d.png)

`report 50100 "PO Correction"
{
    Caption = 'Purchase Order Correction';
    ProcessingOnly = true;

    dataset
    {
        dataitem(Header; "Purchase Header")
        {
            DataItemTableView = where ("Document Type" = filter(Order));
            RequestFilterFields = "No.";

            trigger OnPreDataItem()
            var
                CorrectHeadersQst: Label 'Do you want to correct purchase order %1';
            begin
                if Confirm(StrSubstNo(CorrectHeadersQst, GetFilters())) then
                    CorrectPurchaseOrder("No.");
            end;

        }
    }
}
`

Kind regards,
Waldemar

**Comment by DavidFeldhoff** [comment]
Hi Waldemar, I could reproduce it and it must have to do something with the latest update. I'll check it and update it. Thanks for the quick info!

**Comment by DavidFeldhoff** [comment]
Okay, that was a quick fix, but it shouldn't happen as it stopped nearly each function. The more I'm thankful that you created the issue that fast. 
That shouldn't happen of course. I have to find out why it slipped through my unit tests. 
Thanks!

**Comment by NKarolak** [comment]
I can confirm it's solved ;-)

**Comment by wbrakowski** [comment]
Nice to hear that it is solved now. Have a nice week :-)
