### ISSUE TITLE
Fixing AA0137 doesn't work with AL 7.1.441584

### ISSUE THREAD

**Issue by tinfister** [DavidFeldhoff/al-codeactions#109]
Hi, 
I started action to remove AA0137 warnings in AL 6.x and it worked just fine.
Few days later I have AL 7.1.441584 installed and action does not remove unused variables.
It starts the process, compiles the app and it stops without removing unused variables.

I reverted AL language extension to 6.6.434101 and it works now

**Comment by DavidFeldhoff** [comment]
Hi Tin, nice to hear from you :) 

I found the issue. The alc.exe has a new cop "AL0685" which leads to an invalid json which is returned as errorlog by the alc.exe. Of course my error handling is a shame at that point, so thanks for reporting! 

I've fixed it locally, but I'm currently working on a bigger update. I hope it's fine for you if I wait with publishing the fix until the end of the week?
Until then you're good if you suppress the warning AL0685, by adding the following lines to your app.json.
```
  "suppressWarnings": [
    "AL0685"
  ],
```
Adding the cop to your ruleset wouldn't be enough as I'm not using the ruleset, so it has to be the modification in the app.json to make it work again until I've fixed it. Thanks again and hope to see you next time again at the Beerinar or so :)

Cheers
David

**Comment by tinfister** [comment]
I solved all warnings with older version of AL, no need to hurry.

**Comment by DavidFeldhoff** [comment]
Should be fixed in the latest release. Can you please confirm that?

**Comment by tinfister** [comment]
Yes, it's working for me with AL language extension 7.1.453917
