### ISSUE TITLE
Feature suggestion: Fix warning AA0008 - You must specify open and close parenthesis after

### ISSUE THREAD

**Issue by tinfister** [DavidFeldhoff/al-codeactions#110]
Hi,
compiler throws warning and gives information about line number and starting position of function called without paranthesis. If you know how to get to the end of the function, you could put paranthesis there.

**Comment by DavidFeldhoff** [comment]
Yes, I can make that possible. Don't know if this will make it to the update at the end of the week, but I'll implement it.
FYI:  You can get the end position if you use the error log of the alc.exe instead :)

**Comment by DavidFeldhoff** [comment]
Hi Tin, I'm passing the ball over to you as I've just released it in v1.0.0 :)
Everything works as expected?

Thanks for the suggestion and all the best
David
