### ISSUE TITLE
Wrong invoice rounding in reminder header

### ISSUE THREAD

**Issue by InnoNavSupport** [DavidFeldhoff/al-codeactions#111]
BC 17.2 CH
When creating a reminder the wrong Currency."Invoice Rounding Precision" is used.
table "Reminder Header" -> local procedure ReminderRounding(ReminderHeader: Record "Reminder Header")

Since BC17.2 the procedure calls the procedure GetInvoiceRoundingAmount() which calls GetCurrency(ReminderHeader) to get the currency of the reminder.
But the used variable "ReminderHeader" doesn´t contain the right data because it´s a global.
Either you add the ReminderHeader as a parameter to the procedure GetInvoiceRoundingAmount or you call GetCurrency(Rec) instead of GetCurrency(ReminderHeader)

**Comment by DavidFeldhoff** [comment]
Hi, sorry, but honestly, I don't understand what exactly you're trying to do. 
It seems to me as if you want to report a microsoft base app issue. 

If not, please explain a little bit more what you're trying to do. 
1. What does the code look like before you're doing something with my extension
2. Which command/code action are you using of my extension?
3. What does the code look like now? And what do you want to have changed?

Thanks,
David

**Comment by InnoNavSupport** [comment]
Hello David.
Sorry, my fault. I´ve posted this issue in the wrong channel.
