### ISSUE TITLE
Fix implicit-with missing from command menu

### ISSUE THREAD

**Issue by DavidRoys** [DavidFeldhoff/al-codeactions#112]
I'm using ALCodeActions 0.2.29 with AL Language 7.1.453917 and I can no longer see fix implicit with as an action. The only command I see from ALCodeActions is Fix Cop warnings...

There doesn't appear to be any settings for this extension. I tried removing and re-installing but still don't see it. Is this a bug or something wrong with my setup?

**Comment by DavidFeldhoff** [comment]
Hi David! Nice first name :p
I did remove that command as Andzej (Az AL Dev Tools) added a better alternative which also removes the explicit with statements. :)
So I'd advice you to use the command of his extension.

All the best
David

**Comment by DavidRoys** [comment]
That makes sense! Thanks. :)
