### ISSUE TITLE
[Bug] Create Overload procedure does not work in combination with named return values

### ISSUE THREAD

**Issue by fvet** [DavidFeldhoff/al-codeactions#120]
When creating an overload procedure for a function that has a named return value, the content of current procedure needs to be replaced by a call to the new procedure **+ assignment of the return value**.

![returnvalue](https://user-images.githubusercontent.com/25268332/126181486-5e689e59-506f-4c1a-9c1b-ef1c17749ac2.gif)

Actual (wrong)
`CreateAlert(pcodAlertID, pvarSourceRecord, ptxtMessage, AdditionalRemarks, pintPageID, false);`

Expected
`AlertCreated := CreateAlert(pcodAlertID, pvarSourceRecord, ptxtMessage, AdditionalRemarks, pintPageID, false);`

**Comment by DavidFeldhoff** [comment]
I'll fix that right away. Thanks :)

**Comment by DavidFeldhoff** [comment]
Short update: It's fixed locally for me, but I haven't published it yet as I also started working on #118 and #119 and I'm already pretty far, so I hope to get them published together this week.

**Comment by DavidFeldhoff** [comment]
Unfortunately, #118 and #119 takes a little bit more time to implement which is why I've published a version with #120 and #121 only for now (v1.0.4). But I'm still working on it, I just wanted to take out the pressure.
