### ISSUE TITLE
[Suggestion] Convert option table field to enum

### ISSUE THREAD

**Issue by fvet** [DavidFeldhoff/al-codeactions#122]
It would be nice if we could have a code action that allows (on a table field of datatype 'option') the creation of a new enum (new enum name to be asked via commandpalette) based on the OptionMembers / OptionCaption and replace the datatype of the table field by the new enum (+ remove OptionCaption / OptionMembers)

Before

![image](https://user-images.githubusercontent.com/25268332/126184906-a90516db-c93c-4128-9a75-d6026ba5a7a1.png)

After 

![image](https://user-images.githubusercontent.com/25268332/126184863-16f1efb8-1be2-4990-bd57-46c0213f2335.png)

![image](https://user-images.githubusercontent.com/25268332/126184925-3eb1edc4-0418-439c-95d9-bdf20a357a48.png)

**Comment by DavidFeldhoff** [comment]
Sounds good. I'll add it. But what about the location of the new file? The "CRS: Reorganize - Current file" could be an option, but if some people use it differently.. Maybe it's also an option to place it at the same directory as the current file?

**Comment by DavidFeldhoff** [comment]
Hi Frédéric, I've released a new version v1.0.7 which has this feature included. See the demo in the demo section of my readme.
https://github.com/DavidFeldhoff/al-codeactions#refactor-option-to-enum
I'm looking forward to your feedback!

**Comment by fvet** [comment]
Hi @DavidFeldhoff, thanks for this new feature, it works super!

One small remark:

I tend to add '**, Locked = true**' for blank options (' '), since those require no translations.

So instead of ...

```
value(0; " ")
    {
        Caption = ' ';
    }
```

... I normally add 

```
value(0; " ")
    {
        Caption = ' ', Locked = true;
    }
```

**Comment by DavidFeldhoff** [comment]
That makes much sense indeed. I'll add it definitely.
