### ISSUE TITLE
CodeAction "Extract to procedure" not always available

### ISSUE THREAD

**Issue by jwikman** [DavidFeldhoff/al-codeactions#131]
Now and then I've experienced that the CodeAction "Extract to procedure" is unavailable when I've been selecting some lines of code.
I don't know if this is a limitation that you can resolve, or if it's a VSCode limitation.

This is what I found so far where the CodeAction is gone:
1. Cursor on blank line, after selection
![image](https://user-images.githubusercontent.com/23032645/140328985-ff4587d8-177f-41a7-a872-668184c61368.png)
2. Selection starts on a blank line, before the code starts
![image](https://user-images.githubusercontent.com/23032645/140329273-3ba3ee59-88b3-4f7a-ad67-34047ae34b73.png)
3. Selection includes empty spaces in a line after the code (might be the same as 1. above)
![image](https://user-images.githubusercontent.com/23032645/140329500-4627a3ae-bf42-4d07-9165-105ae9f33623.png)

**Comment by DavidFeldhoff** [comment]
That's most probably a limitation I can resolve. Thanks for reporting this!
I think I'll get to it in 3 weeks as my current 2 weeks are quite full.
Cheers
David

**Comment by jwikman** [comment]
No worries, take your time. I know how to live with it, but you will remove some annoyances if you fix this. :)

**Comment by DavidFeldhoff** [comment]
I created a new version (1.0.10). It wasn't that easy as I thought it would be as the position to rename the procedure afterwards jumped back and forth 😄 
But I think I managed it. If you find any bugs with it, please feel free to come back to me and thanks for contributing :)

**Comment by jwikman** [comment]
Great work @DavidFeldhoff,
The above scenarios works now! 👍
