### ISSUE TITLE
Create Procedure / Event Broken per AL version 8.2.545335

### ISSUE THREAD

**Issue by PeterConijn** [DavidFeldhoff/al-codeactions#132]
Apparently Microsoft made a change in the AL language version (8.2.545335) that breaks the Create Procedure / Create Event code action. All you get is "No code actions available". 

Reverting to the previous AL version (8.1.540594) will make it work again, but I thought you'd might want to know about it.

![afbeelding](https://user-images.githubusercontent.com/47315514/142614608-0f167d36-80b1-4608-a8e5-39b616c5c0aa.png)

![afbeelding](https://user-images.githubusercontent.com/47315514/142614636-5398bf02-db0a-454d-a4e8-ca007dbb4695.png)

**Comment by DavidFeldhoff** [comment]
Of course I want to know that :) Thanks for the fast issue, I'll directly get my hands down on this

**Comment by PeterConijn** [comment]
Anytime! Good luck and thank you for this amazing work-saver.

**Comment by DavidFeldhoff** [comment]
I released a new version 1.0.10 which is compatible with the new AL language extension while still being compatible with the older ones. Thanks again for your fast issue 👏
