### ISSUE TITLE
Copy all (missing) source-table fields to page fields

### ISSUE THREAD

**Issue by christianbraeunlich** [DavidFeldhoff/al-codeactions#134]
Hi, looking for a function that automatically inserts all fields of the SourceTable (or all missing ones) in my Page (e.g. currently focused in vs code).

Thought this project would be a good place to start asking for.

It also might be the case that this already exists and I haven't looked in the right places to find it. Thanks in advance!

![auto-fields](https://user-images.githubusercontent.com/25108568/144706499-4c2d3d2a-98e7-479f-9b8d-7dba0c1c502e.gif)

**Comment by DavidFeldhoff** [comment]
Hi Christian, I just read your review. Thanks for that!! Made my day. 🙂🙂

Regarding your issue, I guess you can use the code action which is delivered by the "AZ AL Dev Tools / AL Code Outline" extension. Just head to the readme and search for the code action part. There's also a gif which explains the "Add multiple fields" action. Is that what you have been looking for? 
https://marketplace.visualstudio.com/items?itemName=andrzejzwierzchowski.al-code-outline

**Comment by christianbraeunlich** [comment]
All thanks to you! 😉
Yes, this is exactly what I was looking for, thanks David! Quite hidden I would like to mention. Have to press "CTRL + ." more often to explore my options. Case closed!
