### ISSUE TITLE
Feature Request: Add Code Action to create an unknown variable

### ISSUE THREAD

**Issue by pungggi** [DavidFeldhoff/al-codeactions#135]
Hello first if all thank you for this great extension.
I feel this feature could enrich the extension and user experience.

A lot of developers start write the code before even a variable exists like

mynewvar := CurrentDateTime();

It would be very good to have a codeaction to create that undefined variable as local or global variable.
I would start easy with just a local variable in a procedure.

What do you think?

**Comment by DavidFeldhoff** [comment]
Hi :)
Yes, I totally agree with you that such a feature enriches the user experience. But there's already an extension that's delivering that feature. Check out the extension of Waldemar: https://marketplace.visualstudio.com/items?itemName=wbrakowski.al-navigator
If there's anything missing, then please share your ideas again with us, but I think the "local variable creation" part is solved by that :)

Best regards
David

**Comment by pungggi** [comment]
Thank you for pointing me to this extension!
