### ISSUE TITLE
Create Procedure Error: Unable to locate target object:

### ISSUE THREAD

**Issue by wbrakowski** [DavidFeldhoff/al-codeactions#140]
Hey David,

I have an error when trying to create a procedure in a very simple codeunit. Usually I am too lazy to file issues, but your error message told me to do so, so I did. 😆 

![image](https://user-images.githubusercontent.com/53928639/180190166-2ae6a46c-79ef-4552-9131-5cb824285885.png)

Peace

**Comment by DavidFeldhoff** [comment]
Hi Waldemar :) Thanks! Then I'd say the message did it's job 😄 
I just tried to reproduce it, but wasn't able to do it. After looking at the code where the error was thrown I noticed that it could happen if the source file is broken. And I see on your screenshot that the closing quote on the object name is missing. Might it be the case that adding the quote there is solving the problem? :)

Cheers,
David

**Comment by wbrakowski** [comment]
Sounds good, thank you. :-)
