### ISSUE TITLE
Extract to procedure error: Cannot read properties of undefined (reading 'end')

### ISSUE THREAD

**Issue by lvanvugt** [DavidFeldhoff/al-codeactions#143]
### Issue
When wanting to `Extract to procedure` I am getting the following error:

`Cannot read properties of undefined (reading 'end')`

This seems to happen in any project I am currently working on.

### Additional info
- I am using rightnow AL CodeActions v1.0.19

**Comment by DavidFeldhoff** [comment]
Looking into it tomorrow. Thanks for the info, Luc!

**Comment by DavidFeldhoff** [comment]
Just looked into it and directly found the issue. It should be fixed now :)
Thanks for directly reporting and hope to catch you at the TechDays for a chat/beer :)
Best regards
David

**Comment by lvanvugt** [comment]
> Just looked into it and directly found the issue. It should be fixed now :)

Great. Tested and working again.

> ... and hope to catch you at the TechDays for a chat/beer

First time meeting in real life, so, we have to. No excuses ;-)
