### ISSUE TITLE
Create procedure and extract to procedure not working

### ISSUE THREAD

**Issue by lvlaanderen** [DavidFeldhoff/al-codeactions#145]
Whenever I try to use these actions I get the following error:
Cannot read properties of undefined (reading 'trackEvent')

I have tested this with the bare minimum extensions installed.
AL Language
v9.5.674382

Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22622
Sandboxed: No

**Comment by DavidFeldhoff** [comment]
Thanks for the info. That does not sound good. I'll look at it directly this evening or tomorrow morning

**Comment by DavidFeldhoff** [comment]
I checked it and I have the same setup as you have, but unfortunately I couldn't reproduce it. But I have a feeling where it could appear which I've fixed. Could you please try and verify if it's working again on your site?

**Comment by lvlaanderen** [comment]
With advanced options it now seems to work, but the basic one doesn't do anything, not even error

**Comment by DavidFeldhoff** [comment]
That's weird, I don't get that.
If you select "No" in both questions showing up by the advanced procdure creation, then the code executes execatly the same as the basic one. And you say that it works with the advanced one and the basic one doesn't do anything? Even if you respond with "No" to both questions?

Can you show my your sample code with which you're trying it? Maybe there's something I'm missing.
If that is also not helping, then I'd be happy if you would spent some time with me and show it to me in a teams session or something similar

**Comment by lvlaanderen** [comment]
I have just tried again, but this time I restarted VSCode instead of a reload, and it's now working 😃
