### ISSUE TITLE
[Bug] Extract to procedure (single line) does not ask for new procedure name

### ISSUE THREAD

**Issue by fvet** [DavidFeldhoff/al-codeactions#155]
@DavidFeldhoff 

If I select one line to extract to a procedure, the code action does not ask for the name of the new procedure, but changes the argument name.

![ExtraToProcedure](https://user-images.githubusercontent.com/25268332/225553266-f4397df6-7cfa-4e92-b795-2d636cde1aa8.gif)

**Comment by DavidFeldhoff** [comment]
Hi Frederic, thanks! I'll look into it. I think next week the fix should be ready.

**Comment by DavidFeldhoff** [comment]
Sorry, there has been some private stuff more important. I hope I can look into it next week

**Comment by DavidFeldhoff** [comment]
It should be fixed with 1.0.29
