### ISSUE TITLE
Extract to procedure - Preceding Comments are missing

### ISSUE THREAD

**Issue by pri-kise** [DavidFeldhoff/al-codeactions#158]
If I mark some code including  preceding comment lines, then the comment lines are missing.
I don't know if this is done on purpose or not, but I personally would prefer the comment to be included if I have it in my selection.

```al
local procedure DoMagicSpaghettiCode(SalesHeader: Record "Sales Header"; var GenJournalLine: Record "Gen. Journal Line")
begin  
    //NOTE: Do some magic, that should be included in the new procedure
   if SalesHeader."Document Type" <> SalesHeader."Document Type"::Invoice then
        exit;
    if not SalesHeader."PTE Custom Field" then
        exit;
```

**Comment by DavidFeldhoff** [comment]
Hey, actually it's currently done on purpose. If there would be two comment lines above the code, but you only mark the second one, then you probably would expect that the second line only would be extracted, right?

**Comment by pri-kise** [comment]
Yeah exactly.

**Comment by pri-kise** [comment]
I checked it and now it works as expected 👍
