### ISSUE TITLE
Generate in-object Permission property

### ISSUE THREAD

**Issue by JeremyVyska** [DavidFeldhoff/al-codeactions#161]
I've been doing a lot of Demo Creation and whatnot code lately that needs to have codeunits that should Insert/Modify a lot of data in tables.  For safety, the permissions are built into the CU itself.

It would be a neat Command Action to be able to build the Permissions property from the code in the Active Editor.  So, detect which objects are accessed and add them all to a permissions string up top, like:

```AL
Permissions = tabledata "Item Journal Template" = rim,
        tabledata "No. Series" = r,
        tabledata "Source Code Setup" = r;
```

It would be extra neat if we could have it autoselect which rimd to use, but even just having all of them and then we edit down manually would be a big time saver.

**Comment by DavidFeldhoff** [comment]
Hi @JeremyVyska, sorry, I missed this one, but to be honest I wasn't very active as well the last time. Anyhow, I just checked your requirement and I think it makes much sense, but it seems that Andrzej already got us covered. Do you agree? Then probably you owe him a drink at TechDays ;) Hope to see you there.

https://github.com/DavidFeldhoff/al-codeactions/assets/53570297/f3642a11-7c8d-44c3-a34c-f40b1066395d

**Comment by DavidFeldhoff** [comment]
I think this one is already covered by the AZ AL Dev Tools
