### ISSUE TITLE
[Create Procedure] adds "internal" even if the caller is in a different app

### ISSUE THREAD

**Issue by dannoe** [DavidFeldhoff/al-codeactions#162]
Given:

- App X uses [depends on] App Y
- Using a multi-project workspace in vscode with both projects open:

Steps to reproduce:

- Inside App X write code to call a non-existing procedure from a codeunit in App Y.
- Use the action "Create Procedure" to create the procedure inside App Y.
- The procedure has the internal modifier set.
- Compiler Warning inside App X that the procedure
- Need to remove the internal modifier in the new procedure in App Y.

**Comment by DavidFeldhoff** [comment]
Hey, thanks for letting me know this one! Currently I hardly find time for developing in my spare time, but I try to make it happen the next weeks.
Best regards
David

**Comment by DavidFeldhoff** [comment]
I fixed it locally and will release it together with a few other improvements soon

**Comment by DavidFeldhoff** [comment]
This "will release it [..] soon" took some time 🙈  
but I finally released it in v1.0.30. Would be happy if you could confirm that it's working as expected. Thanks!

**Comment by dannoe** [comment]
Just tested it and it works as intended. But I found another bug, will open a new issue for it.
