### ISSUE TITLE
Extract Label Tries to Rename Wrong Thing

### ISSUE THREAD

**Issue by mjmatthiesen** [DavidFeldhoff/al-codeactions#165]
Create an error message and add a string. Use extract label (either action). It now tries to rename the line above.

![image](https://github.com/DavidFeldhoff/al-codeactions/assets/16603906/9171a934-0814-4c09-9907-e829b74582ab)

![image](https://github.com/DavidFeldhoff/al-codeactions/assets/16603906/b92a29ee-bfec-4aa9-99f2-d290f03787b8)

**Comment by DavidFeldhoff** [comment]
I just tried to reproduce it, but without success. Doesn't make a difference where I place the cursor or if I mark everything or not. Does it happen all the time for you or just sometimes? And is there something special in that object? Would be happy about some more information to get it fixed. Thanks in advance !

https://github.com/DavidFeldhoff/al-codeactions/assets/53570297/1b1a6d25-62eb-40f7-ab91-6852d72488d6

**Comment by mjmatthiesen** [comment]
Happens always. Location in object doesn't matter. Restarted VS Code entirely to ensure that wasn't the issue, because electron apps do love to be stuck in a bad state. Here's a quick vid in a fresh codeunit.

https://github.com/DavidFeldhoff/al-codeactions/assets/16603906/6d80c8e0-4a14-41ab-8ade-d5ca5ebebc71

Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045


Tried again with everything disabled except for codeactions, az al dev tools, crs al (dependency somewhere?), al language

Everything is current. AL Lang is v12.1.883011

Still happens. Not sure what is causing this. I'm not able to find any cause.

Runtime in the app.json of this project is 11. Tried adding NoImplicitWith, but that didn't change anything, no features otherwise. This happens in every project. Uninstalled and reinstalled the extension, same issue.

**Comment by DavidFeldhoff** [comment]
Thanks for checking. Two more questions: 

1. does it work with v1.0.29 of my extension and latest AZ AL dev tools?
2. I made some changes regarding CR and LF recognition. I assume you are working with crlf line endings, right?

**Comment by mjmatthiesen** [comment]
Line endings are the key. I use LF
With .31 LF does not work, CRLF does.
With .29 they both work.

**Comment by DavidFeldhoff** [comment]
Ah great. I'll look into it, thanks 👍

**Comment by DavidFeldhoff** [comment]
I created a fix for it with v1.0.32. Would be happy if you could test if everything works as expected. Thanks and cheers, David

**Comment by mjmatthiesen** [comment]
Works for me now, thanks!
