### ISSUE TITLE
'Add OnBefore/OnAfter publisher' unavailable 

### ISSUE THREAD

**Issue by fvet** [DavidFeldhoff/al-codeactions#166]
Following #163, I still face issues where in lots of objects, I simply don't get the 'Add OnBefore/OnAfter publisher' codeactions suggestions...

https://github.com/DavidFeldhoff/al-codeactions/assets/25268332/c65cb13d-9ab5-41f1-a133-3e623b31563a

- AL CodeActions: v1.0.30
- AL Language extension for Microsoft Dynamics 365 Business Central: 12.1.883011
- AZ AL Dev Tools/AL Code Outline: 3.0.51

**Comment by fvet** [comment]
Tried to repro in a very basic AL project with limited AL related extensions.
Only got the suggested Code Actions once :(


https://github.com/DavidFeldhoff/al-codeactions/assets/25268332/3b05c743-2656-4805-8e9e-6a2f6ddd786d

**Comment by DavidFeldhoff** [comment]
Hi Frederic, I could reproduce it. Honestly I've no clue why it happened now, as this bug seemed to have been longer in the product 🤔 Anyhow, I just published v1.0.31 which should be available in a few minutes. Could you please confirm that it's working now?

**Comment by fvet** [comment]
Just re-tested and confirm it works.

I was really missing that feature a lot, thanks for the quick fix 🙏🙏
