### ISSUE TITLE
Possible bug in "Reference to Built in functions"

### ISSUE THREAD

**Issue by frottke** [DavidFeldhoff/al-codeactions#169]
Hi @DavidFeldhoff ,

it looks like for me that the feature "[Reference to Built in functions](https://github.com/DavidFeldhoff/al-codeactions?tab=readme-ov-file#references-to-built-in-functions)" is broken, it simply does nothing. I was able to reproduce the bug with the same Item Record. aka. standard answer from the IDE `No definition found for 'Insert'`

All software parts seem to be up to date.
| Software| Version |
|--------|--------|
| Visual Studio Code | 1.84.2|
| AL Language| v12.1.887908|
| AL CodeActions| v1.0.33|
| AZ AL Dev Tools/AL Code Outline| v3.0.53| 

AL runtime per app.json is 10.0 and the BC Version (symbols) is 21.1

**Comment by DavidFeldhoff** [comment]
Hi @frottke , quite old this issue already, but in case it's still up to date: Is it possible that there was no trigger OnInsert on the base table? If there's none, then I don't deliver a definition. I only refer to an trigger OnInsert() Reference.

**Comment by frottke** [comment]
Hi @DavidFeldhoff, that was indeed the issue. Thanks!
