### ISSUE TITLE
Create overload does not work anymore

### ISSUE THREAD

**Issue by jmadrigalTCN** [DavidFeldhoff/al-codeactions#173]
In VSCode with "AL Languaje extension" v: 12.5, "AL-AZ DevTools" v: 3.0.56, and "AL CodeActions" v: 1.0.34, if you choose "Create overload of existing procedure" it does not work.

**Comment by DavidFeldhoff** [comment]
Hello @jmadrigalTCN , I just had a look into it with the latest versions
AL Language extension v13.0.964488
AZ AL Dev Tools v12.0.59
AL CodeActions v1.0.34
But I couldn't find an issue there. Can you please try to reproduce it?

https://github.com/DavidFeldhoff/al-codeactions/assets/53570297/7fdc8984-689c-4c21-b873-5615a89c0521

**Comment by jmadrigalTCN** [comment]
I don't know what happend.
Now it works to me as well.

Next time I'll record a video as you did.

Thank you ever so much.

**Comment by DavidFeldhoff** [comment]
Okay, great, let me know if it happens again.
