### ISSUE TITLE
Slows down other QuickFixes

### ISSUE THREAD

**Issue by aipungggi** [DavidFeldhoff/al-codeactions#174]
This extension slows down other QuickFixes like AL Navigator. When disabling QuickFixes are fast else slow.

**Comment by DavidFeldhoff** [comment]
Hey @aipungggi , can you please explain what happened that it seems to be resolved? I can't find a commit on Waldemars extension that seems to have fixed something and as I didn't change anything I'd be curious if there's still an issue or if it was slow due to something completely different?
