### ISSUE TITLE
Remove unused Variables Error

### ISSUE THREAD

**Issue by Mike-D-117** [DavidFeldhoff/al-codeactions#175]
Hey,

one of my most needed Cleanup is not working atm:

> Method not found: 'Microsoft.Dynamics.Nav.CodeAnalysis.Compilation Microsoft.Dynamics.Nav.CodeAnalysis.Compilation.Create(System.String, System.String, System.Version, System.Nullable`1<System.Guid>, System.Collections.Generic.IEnumerable`1<Microsoft.Dynamics.Nav.CodeAnalysis.SymbolReferenceSpecification>, System.Collections.Generic.IEnumerable`1<Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.SyntaxTree>, Microsoft.Dynamics.Nav.CodeAnalysis.CompilationOptions, Microsoft.Dynamics.Nav.CodeAnalysis.IFileSystem, Microsoft.Dynamics.Nav.CodeAnalysis.DotNet.IDotNetResolverFactory, Microsoft.Dynamics.Nav.CodeAnalysis.IReferenceManager, Boolean)'.

Is there anything I missed to setup or change?

**Comment by christianbraeunlich** [comment]
Yesterday the new al language version was released, and with it some breaking changes.

As a workaround you can switch back to the previous AL language version, which might fix the error atm:
![image](https://github.com/DavidFeldhoff/al-codeactions/assets/25108568/af1c7788-c630-41be-91b5-aa0b9418d2f8)

**Comment by DavidFeldhoff** [comment]
Thanks for the analysis @christianbraeunlich 🙂
Regarding the cleanup tasks, Andrzej (author of the AZ AL Dev Tools) implemented as well a cleanup task after I've implemented it,  which is better then my one, so I'm considering to remove it in the future.
Check out his "Remove Unused Variables from the Active Project" as well
