### ISSUE TITLE
Adding Procedure before the Global var section violates the best practice guide

### ISSUE THREAD

**Issue by IceOnly** [DavidFeldhoff/al-codeactions#58]
The change of 0.2.10 "Procedures are now placed before the global var section if there is no procedure in the file yet." violates the best practice guide:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-structure

**Comment by DavidFeldhoff** [comment]
Oops.. Then we did it wrong for us :)
You can expect a fix soon!

**Comment by DavidFeldhoff** [comment]
Thanks for reporting ! Didn't know that, but now it should be fine :)
