### ISSUE TITLE
Idea: CodeCop/QuickFix for missing permissions

### ISSUE THREAD

**Issue by pri-kise** [DavidFeldhoff/al-codeactions#61]
I don't know if your extensions is the right point to share my idea. 
So please do what you want with it.

Have you thought about an QuickFix for adding missing Permissions to Codeunits or Reports?
After the annoying CodeCop AL0214 there might be the information about which Records/Table are used (Read, Insert, Modify, Delete) inside this object.
I would really love a QuickFix that would add the minimum required  (indirect) permissions.

**Comment by DavidFeldhoff** [comment]
First of all thanks for the suggestion. Ideas are always welcome! :)
But I have to think about that if I could make it possible. I think I will investigate a little bit on that and come back to you then

**Comment by DavidFeldhoff** [comment]
Sorry for not being responsive on this issue. But I don't think I'll add it to my extension at any time. But it sounds that Andrzej wants to add it in his AZ AL Dev Tools Extension as explained here, so I'll close this issue and am looking forward together with you on Andrzejs implementation ;)
https://www.yammer.com/dynamicsnavdev/threads/1155926146334720
