### ISSUE TITLE
Code Actions do not work anymore

### ISSUE THREAD

**Issue by NKarolak** [DavidFeldhoff/al-codeactions#64]
I don't know how and when exactly it happened, but all your app code actions are not provided for me anymore.

![image](https://user-images.githubusercontent.com/34504100/85410435-5f19b280-b567-11ea-80a3-7a7cbf5dc7ee.png)

I am using, as required, the latest versions of your app and of the apps you are depending on:
![image](https://user-images.githubusercontent.com/34504100/85410526-840e2580-b567-11ea-9b4d-0e1f98f74d99.png)

Code actions are enabled for AL Language.

VS Code Version: 1.46.1

Any ideas ...?

**Comment by DavidFeldhoff** [comment]
Hi Natalie, thanks for reporting. I recognized it as well today :( It has something to do with the update of Andrzej's extension. With the version v1.0.49 it works fine. I have to look what has changed there and find a solution.

**Comment by DavidFeldhoff** [comment]
Okay, Andrzej is informed and knows what has happened. And he is - as always - very responsive and helpful that he'll update it. Don't know what I'd do without him :)

**Comment by NKarolak** [comment]
I'm glad to hear. 
I was pretty sure it was my environment only 😅

**Comment by DavidFeldhoff** [comment]
Since Andrzej stepped in yesterday and fixed it, it works for me now again :)

**Comment by NKarolak** [comment]
Confirmed, thanks :-)
