### ISSUE TITLE
Add Result parameter as var to Event

### ISSUE THREAD

**Issue by pri-kise** [DavidFeldhoff/al-codeactions#69]
I think it could be usefult to add Result parameters as var to automatically created events:
```al
procedure TestSomething(Input: Integer) Result: Boolean
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnCheckSomething(Input, Result, IsHandled)
end;
```

This would result in the following Event:
```al
[IntegrationEvent(false, false)]
local procedure OnCheckSomething(Input: Integer; var Result: Boolean;  IsHandled: Boolean)
begin
end;
```
At the moment `Result` is added without `var`.
Then I only have to change the `IsHandled` parameter manually to `var`.

**Comment by DavidFeldhoff** [comment]
I think it's related to #63.

I'm planning to add all parameters with a `var` and jump into the snippet mode, so that you can delete and tab through the var keywords, so that you can decide on your own which parameter should be a `var` one and which not. What do you think of that idea? Would it be fine for you? Or would that be just your second choice?

**Comment by pri-kise** [comment]
I've overseen this issue and the suggested Filter _"add var to variables which contain the following words"_ sounds great for something like `IsHandled`, but I would prefer an additional option to force return variables as var, since they make only sense as `var` in my opinion.

**Comment by DavidFeldhoff** [comment]
Hi pri-kise. Has been some time that you've posted the issue, but maybe it's still an issue for you.
I re-read my issues and thought about making all parameters to var-parameters for events. At least, if it's possible.
So taking up your code sample from above it would result in:
```
[IntegrationEvent(false, false)]
local procedure OnCheckSomething(var Input: Integer; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```
But if you for example have literals or Enum-Options in the argument, these would be of course not var-parameters as your code wouldn't compile anymore ^^. To make it more clear, here's an example:
This
```
procedure TestSomething(Input: Integer) Result: Boolean
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnCheckSomething(Input, Result, 1, 'Hello World', Enum::"Sales Document Type"::Order, IsHandled);
end;
```
will result in
```
[IntegrationEvent(false,false)]
local procedure OnCheckSomething(var Input: Integer; var Result: Boolean; arg1: Integer; arg2: Text; SalesDocumentType: Enum "Sales Document Type"; var IsHandled: Boolean)
begin
end;
```
Is that fine for you?

**Comment by pri-kise** [comment]
I would still prefer a restrictive solution that only adds return parameters or variables passed by refernce as var

**Comment by DavidFeldhoff** [comment]
Okay, I changed it. There will be a new setting:
- varParameters: string[]. Parameters with these names will always be declared as var-Parameters. Default: [ "IsHandled" ]
Furthermore the result variable will always be a var-Parameter.
Hope that fits your needs.

**Comment by pri-kise** [comment]
Sounds great. Thank you. 👍 

One little enhancement for the future might be the support of RegEx, instead of a simple list.
But I still have to think about the use case.
Or maybe a blacklist, like never expose `xRec` as `var `.

**Comment by DavidFeldhoff** [comment]
I added the regex-support as well, so you can put a regex inside the setting ;)
And it's released now. So.. your turn to give feedback :)
