### ISSUE TITLE
German Special Characters in 'Create procedure'

### ISSUE THREAD

**Issue by JulianSchmidtke** [DavidFeldhoff/al-codeactions#71]
When using the 'Create procedure' functionality with variables that for example contain german special characters, then the character is removed from the created parameter.

How to reproduce:

Create a new Codeunit
```
codeunit 99952 Test
{
    procedure MyProcedure()
    var
        Länge: Integer;
    begin
        MySecondProcedure(Länge);
    end;
}
```

Now use 'Create Procedure' on the reference to MySecondProcedure.
That creates this:

```
codeunit 99952 Test
{
	procedure MyProcedure()
	var
		Länge: Integer;
	begin
		MySecondProcedure(Länge);
	end;

	local procedure MySecondProcedure(Lnge: Integer)
	begin
		Error('Procedure MySecondProcedure not implemented.');
	end;
}
```

expected:
```
codeunit 99952 Test
{
	procedure MyProcedure()
	var
		Länge: Integer;
	begin
		MySecondProcedure(Länge);
	end;

	local procedure MySecondProcedure(Länge: Integer)
	begin
		Error('Procedure MySecondProcedure not implemented.');
	end;
}
```

**Comment by DavidFeldhoff** [comment]
Hi Julian, in the future I'll change the ä, ö, ü, ß to ae, oe, ue, and ss, before I remove other characters like brackets or spaces from the variable name. I hope that's fine for you? :)
I'll ship it in the next release. You can expect it this week.
