### ISSUE TITLE
[Idea] Check Procedure Event Name for Affix

### ISSUE THREAD

**Issue by pri-kise** [DavidFeldhoff/al-codeactions#72]
If I use an affix for event signatures in table extensions (e.g. XXX_OnBeforeDoSomething), I don't receive the quickfix for creating an event.

Maybe it is possible to check for the Affix in the AppSourceCop.json?

At the moment i solved this problem for me by using a suffix. (OnBeforeDoSomething_XXX)

What do you think about that?

**Comment by DavidFeldhoff** [comment]
Too much of these good ideas of you, thank you :) but currently too less time to implement :/
I hope I have some more time in the next weeks to get a few of your requests implemented..

**Comment by DavidFeldhoff** [comment]
Didn't hear anything yet, but as I implemented it exactly what you asked for, I'll close this one
