### ISSUE TITLE
The "Unable to get position to insert the procedure" error seems to be back again

### ISSUE THREAD

**Issue by apoyas** [DavidFeldhoff/al-codeactions#81]
The "Unable to get position to insert the procedure" error seems to be back again
(https://github.com/DavidFeldhoff/al-codeactions/issues/70)

"AZ AL Dev Tools/AL Code Outline" v2.0.8
"AL CodeActions" v0.2.14
VSCode v1.47.3
AL Language v3.0.106655

I get the error, when I try to run the "Create Procedure OnTestSomething" action in the following example:
```
codeunit 50000 "Test"
{
    trigger OnRun()
    var
        A: Text;
        B: Integer;
        OK: Boolean;
    begin
        OK := OnTestSomething(A, B);
    end;
    
    var
        myInt: Integer;
}
```

Thanks.

**Comment by DavidFeldhoff** [comment]
Hi, it seems that it was never fixed for codeunits..
It works with the AZ AL Dev Tools Version 1.0.49, but not with the 2.x versions. In version 2.0.4 (where page extensions were fixed) it doesn't work either.
I created a ticket in Andrzej's repository and I hope he can fix that: https://github.com/anzwdev/al-code-outline/issues/171
I'll keep you posted.

**Comment by DavidFeldhoff** [comment]
Sorry, closed accidently :)

**Comment by apoyas** [comment]
> Hi, it seems that it was never fixed for codeunits..
> It works with the AZ AL Dev Tools Version 1.0.49, but not with the 2.x versions. In version 2.0.4 (where page extensions were fixed) it doesn't work either.
> I created a ticket in Andrzej's repository and I hope he can fix that: [anzwdev/al-code-outline#171](https://github.com/anzwdev/al-code-outline/issues/171)
> I'll keep you posted.

Thanks David.
Looking forward for the update :)

**Comment by apoyas** [comment]
Ok, as suggested by Andrzej in related thread (https://github.com/anzwdev/al-code-outline/issues/171#issuecomment-672338687), I've installed the latest VS Code AL Extension from marketplace.
Now everything seems to be working as expected :)
I guess the issue can be closed.
Thanks!

**Comment by DavidFeldhoff** [comment]
Nice, glad to hear :)
