### ISSUE TITLE
Create Procedure: Objects by name not recognized as integer

### ISSUE THREAD

**Issue by NKarolak** [DavidFeldhoff/al-codeactions#84]
Hi David,

Creating a new procedure for 
`MyFunction(Database::"Sales Header");`
or
`MyFunction(Page::"Sales Order");`
etc.

returns 
```
	local procedure MyFunction(arg: Variant)
	begin
		Error('Procedure MyFunction not implemented.');
	end;
```

instead of

```
	local procedure MyFunction(i: Integer)
	begin
		Error('Procedure MyFunction not implemented.');
	end;
```

**Comment by DavidFeldhoff** [comment]
Hi Natalie, the parameters will now be named "TableId", "PageId" and so on and the type will be Integer. Is that fine for you? I'll release it in a few days.

**Comment by NKarolak** [comment]
Perfect, thanks.

**Comment by DavidFeldhoff** [comment]
I just released it. Feel free to test it and close it afterwards :)

**Comment by NKarolak** [comment]
Works like a charm, thanks :-)
