### ISSUE TITLE
Refactor: Move local variable to global

### ISSUE THREAD

**Issue by dannoe** [DavidFeldhoff/al-codeactions#98]

**Comment by DavidFeldhoff** [comment]
Hi and sorry for not reacting directly. During December and the beginning of January I took sime time off ;)
I added the functionality locally already, but would like to test some more. It'll be released probably during the next week.

Thanks for the idea!

**Comment by DavidFeldhoff** [comment]
It's shipped with version 0.2.26. Feel free to test and give me feedback afterwards :)
If I don't here anything from you, I guess it's working as expected and close it myself, but would love to get some feedback ;)

Cheers
David

**Comment by dannoe** [comment]
Hi David, 
thank you for the implementation of my feature request. It took some time for me to test it, because I was busy with some other non-al projects. I used your new function quite often, as I was refactoring code and "globalized" some Management-Codeunit references in my projects. To this date I had no problems using it.

**Comment by DavidFeldhoff** [comment]
Glad to hear, thanks :) Who doesn't know the struggle ;) I'm happy to get any feedback even if it takes some time.
I'll close the issue then. 

All the best
David
