### ISSUE TITLE
Create event publishers in different object

### ISSUE THREAD

**Issue by NKarolak** [DavidFeldhoff/al-codeactions#99]
Addition to #50:

"Create [Integration/Businsess]Event Publisher ..." is not implemented if you intend to create the procedure in another object.

Example:
Working:
`OnMyNewFunction()`

Not working:
`AnotherCodeunitVariable.OnMyNewFunction()`

Use case (thread): https://twitter.com/KarolakNatalie/status/1334783180151394305?s=20

The new event publisher needs to be declared as internal (not global, not local).

**Comment by NKarolak** [comment]
Oops sorry, you've created that yourself already in #93

**Comment by DavidFeldhoff** [comment]
Haha, yes, I already noticed the same gap. And as I saw your post I felt confirmed. I'll for sure add this.

Do you think I should change the access modifier in new procedures as well for other procedures:
`AnotherCodeunitVariable.MyNewFunction`
? Or should there be a quick pick to choose in general between: global, local, internal, protected 🤔

**Comment by NKarolak** [comment]
I prefer to keep it simple. No menu, no setup.
Whenever the procedure needs to be created in another object, then set it to internal.

**Comment by DavidFeldhoff** [comment]
Oh.. totally forgot to give you feedback on this :D Thanks for closing it yourself :)
